[build-system]
build-backend = "uv_build"
requires      = ["uv-build>=0.8,<0.9"]

[project]
name = "we-love-typeid"
version = "0.1.0"
description = "TypeId implementation for the we-love namespace"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.13",
]
dependencies = ["uuid6>=0.1"]

[tool.uv.build-backend]
namespace   = true
module-name = "we_love"

[tool.pyright]
venv     = ".venv"
venvPath = "."
