repos:
- repo: local
  hooks:
  - id: update-north-config
    name: Update north package configuration
    entry: uv run scripts/update_north_config.py
    language: python
    files: ^packages/.*/pyproject\.toml$
    pass_filenames: false
    additional_dependencies: [uv]
  - id: build
    name: Ensure 'uv build' works
    language: python
    files: ^packages/.*
    pass_filenames: false
    entry: uv build --all
    always_run: false
    additional_dependencies: [uv]
  - id: test
    name: run tests
    language: python
    always_run: true
    pass_filenames: false
    entry: uv run pytest
    additional_dependencies: [uv, pytest]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format
