[tool.uv.workspace]
members = [
    "packages/north",
    "packages/north-funcy",
    "packages/north-matchbox",
    "packages/north-registry",
    "packages/north-string",
    "packages/north-typeid",
]

[tool.uv.sources.north]
workspace = true

[dependency-groups]
dev = [
    "north[matchbox,typeid]",
    "pytest>=8.4.1",
    "tomli-w",
    "pre-commit",
    "ruff",
]
