[project]
name            = "north-registry"
version         = "0.1.0"
description     = "Registry and autodiscovery utilities for the north namespace"
requires-python = ">=3.13"
dependencies    = ["pydantic>=2", "north-string"]

[tool.uv.sources]
north-string = { workspace = true }

[build-system]
requires      = ["uv_build>=0.8,<0.9"]
build-backend = "uv_build"

[tool.uv.build-backend]
namespace = true
