[project]
name            = "north-string"
version         = "0.1.0"
description     = "String utilities and case conversion for the north namespace"
requires-python = ">=3.13"
dependencies    = []

[build-system]
requires      = ["uv_build>=0.8,<0.9"]
build-backend = "uv_build"

[tool.uv.build-backend]
namespace = true
