[project]
name            = "north-fzf"
version         = "0.1.0"
description     = "Fzf utilities for the north namespace"
requires-python = ">=3.13"
dependencies    = []

[build-system]
requires      = ["uv_build>=0.8,<0.9"]
build-backend = "uv_build"

[tool.uv.build-backend]
namespace = true
module-name = "north"
